# Generated by Django 5.1 on 2024-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
