# Generated by Django 5.1 on 2024-08-11 14:48

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
